name:                camp
version:             0.1.0
github:              camp-cost/camp
license:             BSD3
author:              anonymised
maintainer:          anonymised
copyright:           anonymised

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Cost-Aware Multiparty Session Protocols
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/camp-cost/camp#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- prettyprinter >= 1.6 && < 1.7
- mtl >= 2.2 && < 2.3
- cubicspline >= 0.1 && < 0.2
- extra >= 1.6 && < 1.7

library:
  source-dirs:
  - src
  - examples
  - benchmarks
  ghc-options:
  - -Wall

executables:
  seq-costs:
    main:                Seq.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
